In [2]:
import numpy as np
np.__version__

'2.4.4'

In [4]:
from numpy import * 

In [5]:
mylist=[0,1,2,3,4,5]
mylist

[0, 1, 2, 3, 4, 5]

In [6]:
type(mylist)

list

In [7]:
arr=np.array(mylist)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,2))  v#2d array with 0 values

SyntaxError: invalid syntax (2261155280.py, line 1)

In [15]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [16]:
np.zeros((5,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [19]:
np.two(3)

AttributeError: module 'numpy' has no attribute 'two'

In [20]:
np

<module 'numpy' from 'C:\\Users\\hp\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [21]:
rand(3)

NameError: name 'rand' is not defined

In [22]:
random.rand(4)

array([0.55800926, 0.87131316, 0.41716692, 0.98154697])

In [23]:
random.rand(3)

array([0.52669905, 0.49657002, 0.76935196])

In [70]:
np.random.rand(int(2))

array([0.06326258, 0.40587789])

In [80]:
np.random.randint(1)

0

In [74]:
np.random.randint(2,10)

4

In [85]:
np.random.randint(1,5,3)

array([4, 3, 2], dtype=int32)

In [36]:
np.random.randint(1,4,2)

array([3, 1], dtype=int32)

In [37]:
np.random.rand(3,5,5)

array([[[0.57280271, 0.71959431, 0.33796494, 0.44822206, 0.06610443],
        [0.48629944, 0.14184514, 0.28707115, 0.09430198, 0.89648541],
        [0.75485677, 0.26100896, 0.33582995, 0.42536806, 0.47603515],
        [0.14123163, 0.66343298, 0.83040712, 0.4386201 , 0.44733002],
        [0.44804622, 0.25447291, 0.38783276, 0.08404644, 0.77286415]],

       [[0.57112316, 0.2571632 , 0.73540101, 0.81380975, 0.84140147],
        [0.46539359, 0.33020856, 0.74603136, 0.92966527, 0.25698675],
        [0.35523688, 0.78359391, 0.19935096, 0.39568889, 0.79458557],
        [0.34549347, 0.00368816, 0.1613506 , 0.63350492, 0.06218301],
        [0.27822309, 0.92932728, 0.97822486, 0.32592249, 0.41335628]],

       [[0.8431513 , 0.5941954 , 0.05488108, 0.44289351, 0.53369408],
        [0.08710622, 0.91266361, 0.09539177, 0.81807424, 0.94524575],
        [0.04472825, 0.46617333, 0.22376119, 0.59207507, 0.314403  ],
        [0.42903982, 0.27975031, 0.059776  , 0.98525554, 0.83452727],
        [0.60060

In [105]:
np.random.randint(5,2,3)

ValueError: low >= high

In [110]:
np.random.randint(-4,5,2)

array([3, 1], dtype=int32)

In [126]:
ri=np.random.randint(10,40,(10,10))
ri

array([[25, 25, 14, 39, 29, 36, 18, 30, 12, 13],
       [38, 29, 35, 24, 31, 26, 23, 22, 32, 31],
       [32, 39, 27, 12, 16, 10, 17, 36, 22, 11],
       [33, 33, 38, 38, 28, 16, 10, 20, 25, 16],
       [32, 39, 28, 33, 21, 31, 37, 10, 13, 30],
       [11, 18, 34, 30, 12, 24, 12, 31, 17, 10],
       [23, 35, 17, 26, 11, 38, 34, 11, 16, 30],
       [19, 34, 36, 30, 34, 28, 12, 19, 19, 17],
       [28, 20, 25, 29, 36, 13, 34, 28, 17, 19],
       [25, 16, 20, 29, 35, 10, 22, 22, 13, 16]], dtype=int32)

In [127]:
len(ri)

10

In [129]:
ri=np.random.randint(10,20,(3,3))
ri

array([[15, 14, 12],
       [16, 13, 19],
       [16, 15, 10]], dtype=int32)

In [130]:
len(ri)

3

In [131]:
ri.shape

(3, 3)

In [135]:
id(ri)

2619418204880

#Slicing in numpy

In [137]:
ri[:]

array([[15, 14, 12],
       [16, 13, 19],
       [16, 15, 10]], dtype=int32)

In [138]:
ri[2]

array([16, 15, 10], dtype=int32)

In [139]:
ri[0]

array([15, 14, 12], dtype=int32)

In [141]:
ri[1]

array([16, 13, 19], dtype=int32)

In [142]:
ri[4]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [143]:
ri[0:3]

array([[15, 14, 12],
       [16, 13, 19],
       [16, 15, 10]], dtype=int32)

In [147]:
ri[0:1]

array([[15, 14, 12]], dtype=int32)

In [39]:
ri_1=np.random.randint(10,20,(10,10))
ri_1

array([[11, 14, 12, 12, 18, 16, 14, 17, 11, 18],
       [11, 16, 13, 18, 12, 11, 11, 15, 14, 16],
       [13, 10, 17, 13, 18, 14, 10, 17, 13, 15],
       [19, 19, 11, 16, 12, 10, 12, 10, 13, 18],
       [14, 15, 10, 14, 17, 17, 12, 10, 18, 14],
       [16, 11, 15, 11, 18, 14, 10, 13, 16, 17],
       [11, 11, 14, 14, 19, 10, 10, 13, 17, 15],
       [13, 11, 11, 19, 13, 18, 15, 11, 10, 13],
       [19, 13, 10, 13, 19, 11, 11, 13, 11, 10],
       [18, 14, 12, 12, 12, 11, 18, 12, 14, 14]], dtype=int32)

In [40]:
ri_1.shape

(10, 10)

In [155]:
print(ri_1)

[[16 16 12 11 14 16 11 11 13 17]
 [13 11 10 13 15 10 12 16 17 13]
 [11 19 10 18 17 19 10 13 18 12]
 [17 16 14 16 15 19 15 17 19 18]
 [13 10 18 15 16 17 14 10 10 12]
 [13 10 15 17 16 12 11 14 19 14]
 [10 13 15 19 13 10 14 18 17 16]
 [14 13 15 14 11 14 18 14 18 12]
 [11 16 16 19 17 15 14 17 10 10]
 [10 14 16 17 19 11 19 14 19 11]]


In [162]:
ri_1[3,8]

np.int32(19)

In [163]:
print(ri_1[3,8])

19


In [164]:
ri_1

array([[16, 16, 12, 11, 14, 16, 11, 11, 13, 17],
       [13, 11, 10, 13, 15, 10, 12, 16, 17, 13],
       [11, 19, 10, 18, 17, 19, 10, 13, 18, 12],
       [17, 16, 14, 16, 15, 19, 15, 17, 19, 18],
       [13, 10, 18, 15, 16, 17, 14, 10, 10, 12],
       [13, 10, 15, 17, 16, 12, 11, 14, 19, 14],
       [10, 13, 15, 19, 13, 10, 14, 18, 17, 16],
       [14, 13, 15, 14, 11, 14, 18, 14, 18, 12],
       [11, 16, 16, 19, 17, 15, 14, 17, 10, 10],
       [10, 14, 16, 17, 19, 11, 19, 14, 19, 11]], dtype=int32)

In [165]:
ri_1[-5]

array([13, 10, 15, 17, 16, 12, 11, 14, 19, 14], dtype=int32)

In [167]:
ri_1[-5:-3]

array([[13, 10, 15, 17, 16, 12, 11, 14, 19, 14],
       [10, 13, 15, 19, 13, 10, 14, 18, 17, 16]], dtype=int32)

In [168]:
print(ri_1[-5,-3])

14


In [169]:
ri_1[::3]

array([[16, 16, 12, 11, 14, 16, 11, 11, 13, 17],
       [17, 16, 14, 16, 15, 19, 15, 17, 19, 18],
       [10, 13, 15, 19, 13, 10, 14, 18, 17, 16],
       [10, 14, 16, 17, 19, 11, 19, 14, 19, 11]], dtype=int32)

In [174]:
ri_1[::-1]

array([[10, 14, 16, 17, 19, 11, 19, 14, 19, 11],
       [11, 16, 16, 19, 17, 15, 14, 17, 10, 10],
       [14, 13, 15, 14, 11, 14, 18, 14, 18, 12],
       [10, 13, 15, 19, 13, 10, 14, 18, 17, 16],
       [13, 10, 15, 17, 16, 12, 11, 14, 19, 14],
       [13, 10, 18, 15, 16, 17, 14, 10, 10, 12],
       [17, 16, 14, 16, 15, 19, 15, 17, 19, 18],
       [11, 19, 10, 18, 17, 19, 10, 13, 18, 12],
       [13, 11, 10, 13, 15, 10, 12, 16, 17, 13],
       [16, 16, 12, 11, 14, 16, 11, 11, 13, 17]], dtype=int32)

In [176]:
ri_1

array([[16, 16, 12, 11, 14, 16, 11, 11, 13, 17],
       [13, 11, 10, 13, 15, 10, 12, 16, 17, 13],
       [11, 19, 10, 18, 17, 19, 10, 13, 18, 12],
       [17, 16, 14, 16, 15, 19, 15, 17, 19, 18],
       [13, 10, 18, 15, 16, 17, 14, 10, 10, 12],
       [13, 10, 15, 17, 16, 12, 11, 14, 19, 14],
       [10, 13, 15, 19, 13, 10, 14, 18, 17, 16],
       [14, 13, 15, 14, 11, 14, 18, 14, 18, 12],
       [11, 16, 16, 19, 17, 15, 14, 17, 10, 10],
       [10, 14, 16, 17, 19, 11, 19, 14, 19, 11]], dtype=int32)

In [177]:
ri_1[::-5]

array([[10, 14, 16, 17, 19, 11, 19, 14, 19, 11],
       [13, 10, 18, 15, 16, 17, 14, 10, 10, 12]], dtype=int32)

In [178]:
ri_1

array([[16, 16, 12, 11, 14, 16, 11, 11, 13, 17],
       [13, 11, 10, 13, 15, 10, 12, 16, 17, 13],
       [11, 19, 10, 18, 17, 19, 10, 13, 18, 12],
       [17, 16, 14, 16, 15, 19, 15, 17, 19, 18],
       [13, 10, 18, 15, 16, 17, 14, 10, 10, 12],
       [13, 10, 15, 17, 16, 12, 11, 14, 19, 14],
       [10, 13, 15, 19, 13, 10, 14, 18, 17, 16],
       [14, 13, 15, 14, 11, 14, 18, 14, 18, 12],
       [11, 16, 16, 19, 17, 15, 14, 17, 10, 10],
       [10, 14, 16, 17, 19, 11, 19, 14, 19, 11]], dtype=int32)

In [179]:
ri_1[2]

array([11, 19, 10, 18, 17, 19, 10, 13, 18, 12], dtype=int32)

In [180]:
ri_1[:,2]

array([12, 10, 10, 14, 18, 15, 15, 15, 16, 16], dtype=int32)

In [182]:
print(ri_1[2])
print(ri_1[:,2])

[11 19 10 18 17 19 10 13 18 12]
[12 10 10 14 18 15 15 15 16 16]


In [183]:
ri_1[:,-1]

array([17, 13, 12, 18, 12, 14, 16, 12, 10, 11], dtype=int32)

In [186]:
ri_1[2:6,5:8]

array([[19, 10, 13],
       [19, 15, 17],
       [17, 14, 10],
       [12, 11, 14]], dtype=int32)

In [42]:
ri_1[-2:-4:-1, -1:-3:-1]

array([[10, 11],
       [13, 10]], dtype=int32)

In [187]:
ri_1[0:2,0:2]

array([[16, 16],
       [13, 11]], dtype=int32)

In [193]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [203]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [204]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [205]:
np.arange(1,13).reshape(6,4)

ValueError: cannot reshape array of size 12 into shape (6,4)

In [208]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [209]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [215]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [216]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])