##ARRAY CREATTION FUNCTIONALITY

In [2]:
import numpy as np
np

<module 'numpy' from 'C:\\Users\\hp\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages\\numpy\\__init__.py'>

In [3]:
#create an array from list

In [4]:
a=np.array([1,2,3])
print("Array a=",a)

Array a= [1 2 3]


In [5]:
#CREATE an array with evenly spaced values

In [6]:
b=np.arange(0,10,2) #values from 0 to 10 with step 2
print("Array b=",b)

Array b= [0 2 4 6 8]


In [7]:
#create an array filled with zeros
d=np.zeros((2,3)) # 2* 3 array of zeros
print("Array d is \n",d)

Array d is 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#create an array filled with ones
e=np.ones((3,2),dtype=int) #3*2 array of ones
print("Array e is \n",e)

Array e is 
 [[1 1]
 [1 1]
 [1 1]]


In [9]:
#Create an identity matrix
f=np.eye(4) # 4*4 Identity matrix
print("Array f is: \n",f)

Array f is: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#ARRAY MANIPULATION FUNCTIONS

In [13]:
#Reshape an array
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3)) # reshape to 1*3 matrix
print("Reshaped array is ",reshaped)

Reshaped array is  [[1 2 3]]


In [14]:
#Reshape an array
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(3,1))# reshape to 3*1 matrix
print("Reshaped array is \n",reshaped)

Reshaped array is 
 [[1]
 [2]
 [3]]


In [15]:
#Flatten the array
f1=np.array([[1,2],[3,4],[5,6],[7,8]])
flattened=np.ravel(f1)   #Flatten to 1D array
print("Flattened array is",flattened)

Flattened array is [1 2 3 4 5 6 7 8]


In [16]:
#Transpose an array
e1=np.array([[1,3],[4,5]])
transposed=np.transpose(e1) # Transpose an array
print("Transposed array is\n",transposed)

Transposed array is
 [[1 4]
 [3 5]]


In [17]:
#Stack array vertically
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2]) #stack a and b vertically
print("Stacked arrays is \n",stacked)

Stacked arrays is 
 [[1 2]
 [3 4]]


In [18]:
#Stack array horizontal
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.hstack([a2,b2]) #stack a and b horizontally
print("Stacked arrays is \n",stacked)

Stacked arrays is 
 [1 2 3 4]


In [19]:
#MATH FUNCTIONS

In [20]:
#Add two arrays
g=np.array([1,2,3,4])
added=np.add(g,2) #Add 2 to each element
print("Added 2 to g \n",added)

Added 2 to g 
 [3 4 5 6]


In [21]:
#square each element
squared=np.power(g,2) #square each elemet
print("Squared g is \n",squared)

Squared g is 
 [ 1  4  9 16]


In [22]:
 #square root each element
sqrt_val=np.sqrt(g) #square root of each element
print("square root of g \n",sqrt_val)


square root of g 
 [1.         1.41421356 1.73205081 2.        ]


In [23]:
print(a)
print(g)
print(a1)

[1 2 3]
[1 2 3 4]
[1 2 3]


In [24]:
#Dot product of two arrays
a3=np.array([1,2,3])
dot_product=np.dot(a1,a) #Dot product of a and a1
print("Dot product of a and a1 is \n",dot_product)

Dot product of a and a1 is 
 14


In [25]:
a3=np.array([1,2,3])
dot_product=np.dot(a1,g) #Dot product of a and a1
print("Dot product of a and g is \n",dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [26]:
#STATISTICAL FUNCTIONS

In [27]:
#Mean
s=np.array([1,2,3,4])
mean=np.mean(s)
print("mean of s is ",mean)

mean of s is  2.5


In [28]:
#Standard deviation of array
std_dev=np.std(s)
print("standard deviation of s is ",std_dev)

standard deviation of s is  1.118033988749895


In [29]:
#Standard deviation of array
var=np.var(s)
print(" variance of s is ",var)

 variance of s is  1.25


In [30]:
#Minimum element of an array
mini=np.min(s)
print("minimum value of s is ",mini)

minimum value of s is  1


In [31]:
#Maximum element of an array
max=np.max(s)
print("max value of s is ",max)

max value of s is  4


In [32]:
#RANDOM SAMPLING FUNCTIONS

In [33]:
#Generate random values between 0 and 1
random_vals=np.random.rand(3) #Array of 3 random values between 0 and 1
print("random values are ",random_vals)

random values are  [0.97205207 0.30449021 0.98453753]


In [34]:
#set seed for reproducibility
np.random.seed(0)
#Generate random values between 0 and 1
random_vals=np.random.rand(3) #Array of 3 random values between 0 and 1
print("random values are ",random_vals)

random values are  [0.5488135  0.71518937 0.60276338]


In [35]:
#Generate random integers
rand_ints=np.random.randint(0,10,size=5) #Random integers between 0 to 10
print("random values are ",rand_ints)

random values are  [3 7 9 3 5]


In [36]:
#set seed for reproducibility
np.random.seed(0)

#Generate random integers
rand_ints=np.random.randint(0,10,size=5) #Random integers between 0 to 10
print("random values are ",rand_ints)

random values are  [5 0 3 3 7]


In [37]:
# 7. Boolean & Logical Functions

In [39]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True]) 
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [1]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

NameError: name 'np' is not defined

In [ ]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

In [ ]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

In [ ]:
# 8. Set Operations

In [ ]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

In [ ]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

In [ ]:
# 9. Array Attribute Functions

In [ ]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


In [ ]:
# 10. Other Functions

In [ ]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

In [ ]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

In [2]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

NameError: name 'np' is not defined